//go:build !ignore_autogenerated

/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPointInfo) DeepCopyInto(out *AccessPointInfo) {
	*out = *in
	if in.PosixUser != nil {
		in, out := &in.PosixUser, &out.PosixUser
		*out = new(PosixUser)
		(*in).DeepCopyInto(*out)
	}
	if in.RootDirectory != nil {
		in, out := &in.RootDirectory, &out.RootDirectory
		*out = new(RootDirectory)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPointInfo.
func (in *AccessPointInfo) DeepCopy() *AccessPointInfo {
	if in == nil {
		return nil
	}
	out := new(AccessPointInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CreationInfo) DeepCopyInto(out *CreationInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CreationInfo.
func (in *CreationInfo) DeepCopy() *CreationInfo {
	if in == nil {
		return nil
	}
	out := new(CreationInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EFSNamespace) DeepCopyInto(out *EFSNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EFSNamespace.
func (in *EFSNamespace) DeepCopy() *EFSNamespace {
	if in == nil {
		return nil
	}
	out := new(EFSNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EFSNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EFSNamespaceCondition) DeepCopyInto(out *EFSNamespaceCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EFSNamespaceCondition.
func (in *EFSNamespaceCondition) DeepCopy() *EFSNamespaceCondition {
	if in == nil {
		return nil
	}
	out := new(EFSNamespaceCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EFSNamespaceList) DeepCopyInto(out *EFSNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EFSNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EFSNamespaceList.
func (in *EFSNamespaceList) DeepCopy() *EFSNamespaceList {
	if in == nil {
		return nil
	}
	out := new(EFSNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EFSNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EFSNamespaceSpec) DeepCopyInto(out *EFSNamespaceSpec) {
	*out = *in
	if in.ProvisionedThroughputInMibps != nil {
		in, out := &in.ProvisionedThroughputInMibps, &out.ProvisionedThroughputInMibps
		*out = new(float64)
		**out = **in
	}
	if in.Encrypted != nil {
		in, out := &in.Encrypted, &out.Encrypted
		*out = new(bool)
		**out = **in
	}
	if in.MountTargets != nil {
		in, out := &in.MountTargets, &out.MountTargets
		*out = new(MountTargetConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AccessPoints != nil {
		in, out := &in.AccessPoints, &out.AccessPoints
		*out = make([]AccessPointInfo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EFSNamespaceSpec.
func (in *EFSNamespaceSpec) DeepCopy() *EFSNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(EFSNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EFSNamespaceStatus) DeepCopyInto(out *EFSNamespaceStatus) {
	*out = *in
	if in.MountTargets != nil {
		in, out := &in.MountTargets, &out.MountTargets
		*out = make([]MountTargetStatus, len(*in))
		copy(*out, *in)
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]EFSNamespaceCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EFSNamespaceStatus.
func (in *EFSNamespaceStatus) DeepCopy() *EFSNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(EFSNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountTargetConfig) DeepCopyInto(out *MountTargetConfig) {
	*out = *in
	if in.SubnetIDs != nil {
		in, out := &in.SubnetIDs, &out.SubnetIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupIDs != nil {
		in, out := &in.SecurityGroupIDs, &out.SecurityGroupIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountTargetConfig.
func (in *MountTargetConfig) DeepCopy() *MountTargetConfig {
	if in == nil {
		return nil
	}
	out := new(MountTargetConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MountTargetStatus) DeepCopyInto(out *MountTargetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MountTargetStatus.
func (in *MountTargetStatus) DeepCopy() *MountTargetStatus {
	if in == nil {
		return nil
	}
	out := new(MountTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PosixUser) DeepCopyInto(out *PosixUser) {
	*out = *in
	if in.SecondaryGIDs != nil {
		in, out := &in.SecondaryGIDs, &out.SecondaryGIDs
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PosixUser.
func (in *PosixUser) DeepCopy() *PosixUser {
	if in == nil {
		return nil
	}
	out := new(PosixUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RootDirectory) DeepCopyInto(out *RootDirectory) {
	*out = *in
	if in.CreationInfo != nil {
		in, out := &in.CreationInfo, &out.CreationInfo
		*out = new(CreationInfo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RootDirectory.
func (in *RootDirectory) DeepCopy() *RootDirectory {
	if in == nil {
		return nil
	}
	out := new(RootDirectory)
	in.DeepCopyInto(out)
	return out
}
