// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/efs-ns (interfaces: NamespaceFileSystemManager,PVCTracker,FinalizerManager)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	efsns "github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/efs-ns"
	v1 "k8s.io/api/core/v1"
)

// MockNamespaceFileSystemManager is a mock of NamespaceFileSystemManager interface.
type MockNamespaceFileSystemManager struct {
	ctrl     *gomock.Controller
	recorder *MockNamespaceFileSystemManagerMockRecorder
}

// MockNamespaceFileSystemManagerMockRecorder is the mock recorder for MockNamespaceFileSystemManager.
type MockNamespaceFileSystemManagerMockRecorder struct {
	mock *MockNamespaceFileSystemManager
}

// NewMockNamespaceFileSystemManager creates a new mock instance.
func NewMockNamespaceFileSystemManager(ctrl *gomock.Controller) *MockNamespaceFileSystemManager {
	mock := &MockNamespaceFileSystemManager{ctrl: ctrl}
	mock.recorder = &MockNamespaceFileSystemManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamespaceFileSystemManager) EXPECT() *MockNamespaceFileSystemManagerMockRecorder {
	return m.recorder
}

// CreateOrGetFileSystemForNamespace mocks base method.
func (m *MockNamespaceFileSystemManager) CreateOrGetFileSystemForNamespace(arg0 context.Context, arg1 string, arg2 *efsns.FileSystemOptions) (*efsns.FileSystemInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrGetFileSystemForNamespace", arg0, arg1, arg2)
	ret0, _ := ret[0].(*efsns.FileSystemInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrGetFileSystemForNamespace indicates an expected call of CreateOrGetFileSystemForNamespace.
func (mr *MockNamespaceFileSystemManagerMockRecorder) CreateOrGetFileSystemForNamespace(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrGetFileSystemForNamespace", reflect.TypeOf((*MockNamespaceFileSystemManager)(nil).CreateOrGetFileSystemForNamespace), arg0, arg1, arg2)
}

// DeleteFileSystemForNamespace mocks base method.
func (m *MockNamespaceFileSystemManager) DeleteFileSystemForNamespace(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFileSystemForNamespace", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFileSystemForNamespace indicates an expected call of DeleteFileSystemForNamespace.
func (mr *MockNamespaceFileSystemManagerMockRecorder) DeleteFileSystemForNamespace(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileSystemForNamespace", reflect.TypeOf((*MockNamespaceFileSystemManager)(nil).DeleteFileSystemForNamespace), arg0, arg1, arg2)
}

// GetFileSystemInfo mocks base method.
func (m *MockNamespaceFileSystemManager) GetFileSystemInfo(arg0 context.Context, arg1 string) (*efsns.FileSystemInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileSystemInfo", arg0, arg1)
	ret0, _ := ret[0].(*efsns.FileSystemInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileSystemInfo indicates an expected call of GetFileSystemInfo.
func (mr *MockNamespaceFileSystemManagerMockRecorder) GetFileSystemInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileSystemInfo", reflect.TypeOf((*MockNamespaceFileSystemManager)(nil).GetFileSystemInfo), arg0, arg1)
}

// ListFileSystemsForNamespace mocks base method.
func (m *MockNamespaceFileSystemManager) ListFileSystemsForNamespace(arg0 context.Context, arg1 string) ([]*efsns.FileSystemInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFileSystemsForNamespace", arg0, arg1)
	ret0, _ := ret[0].([]*efsns.FileSystemInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFileSystemsForNamespace indicates an expected call of ListFileSystemsForNamespace.
func (mr *MockNamespaceFileSystemManagerMockRecorder) ListFileSystemsForNamespace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFileSystemsForNamespace", reflect.TypeOf((*MockNamespaceFileSystemManager)(nil).ListFileSystemsForNamespace), arg0, arg1)
}

// SyncFromAWS mocks base method.
func (m *MockNamespaceFileSystemManager) SyncFromAWS(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncFromAWS", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncFromAWS indicates an expected call of SyncFromAWS.
func (mr *MockNamespaceFileSystemManagerMockRecorder) SyncFromAWS(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncFromAWS", reflect.TypeOf((*MockNamespaceFileSystemManager)(nil).SyncFromAWS), arg0)
}

// MockPVCTracker is a mock of PVCTracker interface.
type MockPVCTracker struct {
	ctrl     *gomock.Controller
	recorder *MockPVCTrackerMockRecorder
}

// MockPVCTrackerMockRecorder is the mock recorder for MockPVCTracker.
type MockPVCTrackerMockRecorder struct {
	mock *MockPVCTracker
}

// NewMockPVCTracker creates a new mock instance.
func NewMockPVCTracker(ctrl *gomock.Controller) *MockPVCTracker {
	mock := &MockPVCTracker{ctrl: ctrl}
	mock.recorder = &MockPVCTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPVCTracker) EXPECT() *MockPVCTrackerMockRecorder {
	return m.recorder
}

// AddPVC mocks base method.
func (m *MockPVCTracker) AddPVC(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPVC", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPVC indicates an expected call of AddPVC.
func (mr *MockPVCTrackerMockRecorder) AddPVC(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPVC", reflect.TypeOf((*MockPVCTracker)(nil).AddPVC), arg0, arg1, arg2, arg3)
}

// GetPVCCount mocks base method.
func (m *MockPVCTracker) GetPVCCount(arg0 context.Context, arg1 string) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPVCCount", arg0, arg1)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPVCCount indicates an expected call of GetPVCCount.
func (mr *MockPVCTrackerMockRecorder) GetPVCCount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPVCCount", reflect.TypeOf((*MockPVCTracker)(nil).GetPVCCount), arg0, arg1)
}

// ListPVCsInNamespace mocks base method.
func (m *MockPVCTracker) ListPVCsInNamespace(arg0 context.Context, arg1 string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPVCsInNamespace", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPVCsInNamespace indicates an expected call of ListPVCsInNamespace.
func (mr *MockPVCTrackerMockRecorder) ListPVCsInNamespace(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPVCsInNamespace", reflect.TypeOf((*MockPVCTracker)(nil).ListPVCsInNamespace), arg0, arg1)
}

// RemovePVC mocks base method.
func (m *MockPVCTracker) RemovePVC(arg0 context.Context, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePVC", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemovePVC indicates an expected call of RemovePVC.
func (mr *MockPVCTrackerMockRecorder) RemovePVC(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePVC", reflect.TypeOf((*MockPVCTracker)(nil).RemovePVC), arg0, arg1, arg2)
}

// SyncWithCluster mocks base method.
func (m *MockPVCTracker) SyncWithCluster(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncWithCluster", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncWithCluster indicates an expected call of SyncWithCluster.
func (mr *MockPVCTrackerMockRecorder) SyncWithCluster(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncWithCluster", reflect.TypeOf((*MockPVCTracker)(nil).SyncWithCluster), arg0)
}

// MockFinalizerManager is a mock of FinalizerManager interface.
type MockFinalizerManager struct {
	ctrl     *gomock.Controller
	recorder *MockFinalizerManagerMockRecorder
}

// MockFinalizerManagerMockRecorder is the mock recorder for MockFinalizerManager.
type MockFinalizerManagerMockRecorder struct {
	mock *MockFinalizerManager
}

// NewMockFinalizerManager creates a new mock instance.
func NewMockFinalizerManager(ctrl *gomock.Controller) *MockFinalizerManager {
	mock := &MockFinalizerManager{ctrl: ctrl}
	mock.recorder = &MockFinalizerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinalizerManager) EXPECT() *MockFinalizerManagerMockRecorder {
	return m.recorder
}

// AddFinalizer mocks base method.
func (m *MockFinalizerManager) AddFinalizer(arg0 context.Context, arg1 *v1.PersistentVolumeClaim) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFinalizer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFinalizer indicates an expected call of AddFinalizer.
func (mr *MockFinalizerManagerMockRecorder) AddFinalizer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFinalizer", reflect.TypeOf((*MockFinalizerManager)(nil).AddFinalizer), arg0, arg1)
}

// AddNamespaceFinalizer mocks base method.
func (m *MockFinalizerManager) AddNamespaceFinalizer(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNamespaceFinalizer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNamespaceFinalizer indicates an expected call of AddNamespaceFinalizer.
func (mr *MockFinalizerManagerMockRecorder) AddNamespaceFinalizer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNamespaceFinalizer", reflect.TypeOf((*MockFinalizerManager)(nil).AddNamespaceFinalizer), arg0, arg1)
}

// ProcessFinalization mocks base method.
func (m *MockFinalizerManager) ProcessFinalization(arg0 context.Context, arg1 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessFinalization", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessFinalization indicates an expected call of ProcessFinalization.
func (mr *MockFinalizerManagerMockRecorder) ProcessFinalization(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessFinalization", reflect.TypeOf((*MockFinalizerManager)(nil).ProcessFinalization), arg0, arg1)
}

// RemoveFinalizer mocks base method.
func (m *MockFinalizerManager) RemoveFinalizer(arg0 context.Context, arg1 *v1.PersistentVolumeClaim) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFinalizer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFinalizer indicates an expected call of RemoveFinalizer.
func (mr *MockFinalizerManagerMockRecorder) RemoveFinalizer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFinalizer", reflect.TypeOf((*MockFinalizerManager)(nil).RemoveFinalizer), arg0, arg1)
}

// RemoveNamespaceFinalizer mocks base method.
func (m *MockFinalizerManager) RemoveNamespaceFinalizer(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNamespaceFinalizer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveNamespaceFinalizer indicates an expected call of RemoveNamespaceFinalizer.
func (mr *MockFinalizerManagerMockRecorder) RemoveNamespaceFinalizer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNamespaceFinalizer", reflect.TypeOf((*MockFinalizerManager)(nil).RemoveNamespaceFinalizer), arg0, arg1)
}
