// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/cloud (interfaces: Cloud)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	cloud "github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/cloud"
)

// MockCloud is a mock of Cloud interface.
type MockCloud struct {
	ctrl     *gomock.Controller
	recorder *MockCloudMockRecorder
}

// MockCloudMockRecorder is the mock recorder for MockCloud.
type MockCloudMockRecorder struct {
	mock *MockCloud
}

// NewMockCloud creates a new mock instance.
func NewMockCloud(ctrl *gomock.Controller) *MockCloud {
	mock := &MockCloud{ctrl: ctrl}
	mock.recorder = &MockCloudMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloud) EXPECT() *MockCloudMockRecorder {
	return m.recorder
}

// CreateAccessPoint mocks base method.
func (m *MockCloud) CreateAccessPoint(arg0 context.Context, arg1 string, arg2 *cloud.AccessPointOptions) (*cloud.AccessPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessPoint", arg0, arg1, arg2)
	ret0, _ := ret[0].(*cloud.AccessPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessPoint indicates an expected call of CreateAccessPoint.
func (mr *MockCloudMockRecorder) CreateAccessPoint(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessPoint", reflect.TypeOf((*MockCloud)(nil).CreateAccessPoint), arg0, arg1, arg2)
}

// CreateFileSystem mocks base method.
func (m *MockCloud) CreateFileSystem(arg0 context.Context, arg1 string, arg2 *cloud.FileSystemOptions) (*cloud.FileSystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFileSystem", arg0, arg1, arg2)
	ret0, _ := ret[0].(*cloud.FileSystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFileSystem indicates an expected call of CreateFileSystem.
func (mr *MockCloudMockRecorder) CreateFileSystem(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFileSystem", reflect.TypeOf((*MockCloud)(nil).CreateFileSystem), arg0, arg1, arg2)
}

// CreateMountTarget mocks base method.
func (m *MockCloud) CreateMountTarget(arg0 context.Context, arg1, arg2, arg3 string) (*cloud.MountTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMountTarget", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*cloud.MountTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMountTarget indicates an expected call of CreateMountTarget.
func (mr *MockCloudMockRecorder) CreateMountTarget(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMountTarget", reflect.TypeOf((*MockCloud)(nil).CreateMountTarget), arg0, arg1, arg2, arg3)
}

// DeleteAccessPoint mocks base method.
func (m *MockCloud) DeleteAccessPoint(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessPoint", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessPoint indicates an expected call of DeleteAccessPoint.
func (mr *MockCloudMockRecorder) DeleteAccessPoint(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessPoint", reflect.TypeOf((*MockCloud)(nil).DeleteAccessPoint), arg0, arg1)
}

// DeleteFileSystem mocks base method.
func (m *MockCloud) DeleteFileSystem(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFileSystem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFileSystem indicates an expected call of DeleteFileSystem.
func (mr *MockCloudMockRecorder) DeleteFileSystem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileSystem", reflect.TypeOf((*MockCloud)(nil).DeleteFileSystem), arg0, arg1)
}

// DeleteMountTarget mocks base method.
func (m *MockCloud) DeleteMountTarget(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMountTarget", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMountTarget indicates an expected call of DeleteMountTarget.
func (mr *MockCloudMockRecorder) DeleteMountTarget(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMountTarget", reflect.TypeOf((*MockCloud)(nil).DeleteMountTarget), arg0, arg1)
}

// DescribeAccessPoint mocks base method.
func (m *MockCloud) DescribeAccessPoint(arg0 context.Context, arg1 string) (*cloud.AccessPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAccessPoint", arg0, arg1)
	ret0, _ := ret[0].(*cloud.AccessPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAccessPoint indicates an expected call of DescribeAccessPoint.
func (mr *MockCloudMockRecorder) DescribeAccessPoint(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAccessPoint", reflect.TypeOf((*MockCloud)(nil).DescribeAccessPoint), arg0, arg1)
}

// DescribeFileSystem mocks base method.
func (m *MockCloud) DescribeFileSystem(arg0 context.Context, arg1 string) (*cloud.FileSystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeFileSystem", arg0, arg1)
	ret0, _ := ret[0].(*cloud.FileSystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeFileSystem indicates an expected call of DescribeFileSystem.
func (mr *MockCloudMockRecorder) DescribeFileSystem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeFileSystem", reflect.TypeOf((*MockCloud)(nil).DescribeFileSystem), arg0, arg1)
}

// DescribeFileSystems mocks base method.
func (m *MockCloud) DescribeFileSystems(arg0 context.Context, arg1 string, arg2 int32) ([]*cloud.FileSystem, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeFileSystems", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*cloud.FileSystem)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DescribeFileSystems indicates an expected call of DescribeFileSystems.
func (mr *MockCloudMockRecorder) DescribeFileSystems(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeFileSystems", reflect.TypeOf((*MockCloud)(nil).DescribeFileSystems), arg0, arg1, arg2)
}

// DescribeMountTargets mocks base method.
func (m *MockCloud) DescribeMountTargets(arg0 context.Context, arg1, arg2 string) (*cloud.MountTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeMountTargets", arg0, arg1, arg2)
	ret0, _ := ret[0].(*cloud.MountTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeMountTargets indicates an expected call of DescribeMountTargets.
func (mr *MockCloudMockRecorder) DescribeMountTargets(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeMountTargets", reflect.TypeOf((*MockCloud)(nil).DescribeMountTargets), arg0, arg1, arg2)
}

// FindAccessPointByClientToken mocks base method.
func (m *MockCloud) FindAccessPointByClientToken(arg0 context.Context, arg1, arg2 string) (*cloud.AccessPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAccessPointByClientToken", arg0, arg1, arg2)
	ret0, _ := ret[0].(*cloud.AccessPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAccessPointByClientToken indicates an expected call of FindAccessPointByClientToken.
func (mr *MockCloudMockRecorder) FindAccessPointByClientToken(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAccessPointByClientToken", reflect.TypeOf((*MockCloud)(nil).FindAccessPointByClientToken), arg0, arg1, arg2)
}

// FindFileSystemsByTags mocks base method.
func (m *MockCloud) FindFileSystemsByTags(arg0 context.Context, arg1 map[string]string) ([]*cloud.FileSystem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFileSystemsByTags", arg0, arg1)
	ret0, _ := ret[0].([]*cloud.FileSystem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFileSystemsByTags indicates an expected call of FindFileSystemsByTags.
func (mr *MockCloudMockRecorder) FindFileSystemsByTags(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFileSystemsByTags", reflect.TypeOf((*MockCloud)(nil).FindFileSystemsByTags), arg0, arg1)
}

// GetClusterSecurityGroup mocks base method.
func (m *MockCloud) GetClusterSecurityGroup(arg0 context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterSecurityGroup", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterSecurityGroup indicates an expected call of GetClusterSecurityGroup.
func (mr *MockCloudMockRecorder) GetClusterSecurityGroup(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterSecurityGroup", reflect.TypeOf((*MockCloud)(nil).GetClusterSecurityGroup), arg0)
}

// GetClusterSubnets mocks base method.
func (m *MockCloud) GetClusterSubnets(arg0 context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterSubnets", arg0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterSubnets indicates an expected call of GetClusterSubnets.
func (mr *MockCloudMockRecorder) GetClusterSubnets(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterSubnets", reflect.TypeOf((*MockCloud)(nil).GetClusterSubnets), arg0)
}

// GetFileSystemTags mocks base method.
func (m *MockCloud) GetFileSystemTags(arg0 context.Context, arg1 string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileSystemTags", arg0, arg1)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileSystemTags indicates an expected call of GetFileSystemTags.
func (mr *MockCloudMockRecorder) GetFileSystemTags(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileSystemTags", reflect.TypeOf((*MockCloud)(nil).GetFileSystemTags), arg0, arg1)
}

// GetMetadata mocks base method.
func (m *MockCloud) GetMetadata() cloud.MetadataService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata")
	ret0, _ := ret[0].(cloud.MetadataService)
	return ret0
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockCloudMockRecorder) GetMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockCloud)(nil).GetMetadata))
}

// ListAccessPoints mocks base method.
func (m *MockCloud) ListAccessPoints(arg0 context.Context, arg1 string) ([]*cloud.AccessPoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessPoints", arg0, arg1)
	ret0, _ := ret[0].([]*cloud.AccessPoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessPoints indicates an expected call of ListAccessPoints.
func (mr *MockCloudMockRecorder) ListAccessPoints(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessPoints", reflect.TypeOf((*MockCloud)(nil).ListAccessPoints), arg0, arg1)
}

// ListMountTargets mocks base method.
func (m *MockCloud) ListMountTargets(arg0 context.Context, arg1 string) ([]*cloud.MountTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMountTargets", arg0, arg1)
	ret0, _ := ret[0].([]*cloud.MountTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMountTargets indicates an expected call of ListMountTargets.
func (mr *MockCloudMockRecorder) ListMountTargets(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMountTargets", reflect.TypeOf((*MockCloud)(nil).ListMountTargets), arg0, arg1)
}

// WaitForFileSystemAvailable mocks base method.
func (m *MockCloud) WaitForFileSystemAvailable(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForFileSystemAvailable", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForFileSystemAvailable indicates an expected call of WaitForFileSystemAvailable.
func (mr *MockCloudMockRecorder) WaitForFileSystemAvailable(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForFileSystemAvailable", reflect.TypeOf((*MockCloud)(nil).WaitForFileSystemAvailable), arg0, arg1)
}

// WaitForMountTargetsAvailable mocks base method.
func (m *MockCloud) WaitForMountTargetsAvailable(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WaitForMountTargetsAvailable", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WaitForMountTargetsAvailable indicates an expected call of WaitForMountTargetsAvailable.
func (mr *MockCloudMockRecorder) WaitForMountTargetsAvailable(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForMountTargetsAvailable", reflect.TypeOf((*MockCloud)(nil).WaitForMountTargetsAvailable), arg0, arg1)
}
